### ISSUE TITLE
cannot find module after nam install

### ISSUE THREAD

**Issue by bryanyang0528** [jstrinko/glipbot#7]
Cannot find module 'lodish' and 'yandex-translate'
<img width="1005" alt="screen shot 2016-10-20 at 11 16 39" src="https://cloud.githubusercontent.com/assets/5171607/19545384/456de18e-96b8-11e6-8551-987f831ec07c.png">
<img width="527" alt="screen shot 2016-10-20 at 11 21 38" src="https://cloud.githubusercontent.com/assets/5171607/19545387/4b2d240e-96b8-11e6-8cac-a7600e09c26a.png">

**Comment by jstrinko** [comment]
This has been fixed. Thanks!
